return {
	-- 作用：让blink.nvim可以兼容cmp.nvim的补全源
	-- 网址：https://github.com/nanotee/nvim-if-lua-compat
	-- {
	-- 	'saghen/blink.compat',
	-- 	version = '*',
	-- 	lazy = true,
	-- },

	-- {
	-- 	'saghen/blink.cmp',
	-- 	version = '0.*',
	-- 	dependencies = {
	-- 		-- 添加cmp源
	-- 		-- { '' },
	-- 	},
	-- 	sources = {
	-- 		-- remember to enable your providers here
	-- 		default = { 'lsp', 'path', 'snippets', 'buffer', 'cmp-im' },
	-- 		providers = {
	-- 			-- create provider
	-- 			-- digraphs = {
	-- 			-- 	-- IMPORTANT: use the same name as you would for nvim-cmp
	-- 			-- 	name = 'cmp-im',
	-- 			-- 	module = 'blink.compat.source',
	-- 			--
	-- 			-- 	-- all blink.cmp source config options work as normal:
	-- 			-- 	score_offset = -3,
	-- 			--
	-- 			-- 	-- this table is passed directly to the proxied completion source
	-- 			-- 	-- as the `option` field in nvim-cmp's source config
	-- 			-- 	--
	-- 			-- 	-- this is NOT the same as the opts in a plugin's lazy.nvim spec
	-- 			-- 	opts = {
	-- 			-- 		-- this is an option from cmp-digraphs
	-- 			-- 		cache_digraphs_on_start = true,
	-- 			--
	-- 			-- 		-- If you'd like to use a `name` that does not exactly match nvim-cmp,
	-- 			-- 		-- set `cmp_name` to the name you would use for nvim-cmp, for instance:
	-- 			-- 		-- cmp_name = "digraphs"
	-- 			-- 		-- then, you can set the source's `name` to whatever you like.
	-- 			-- 	},
	-- 			-- },
	-- 		},
	-- 	},
	-- },
}
