return {
	-- 作用：用于简化neovim的lsp的配置
	-- 网址：https://github.com/neovim/nvim-lspconfig
	-- {
		'neovim/nvim-lspconfig',                   -- Neovim官方LSP配置插件
		-- dependencies = {
		-- 	'saghen/blink.cmp',                    -- 补全增强插件
		-- 	"https://git.sr.ht/~whynothugo/lsp_lines.nvim", -- 诊断信息行内显示
		-- 	-- "mfussenegger/nvim-jdtls",
		-- },
		-- event = { "BufReadPost", "BufNewFile" }, -- 文件打开时初始化
		--
		-- keys = {                           -- 快捷键映射
		-- 	{ "<leader>ls", mode = "n", "<cmd>LspStart<cr>", desc = "启动LSP服务" },
		-- 	{ "<leader>lt", mode = "n", "<cmd>LspStop<cr>", desc = "停止LSP服务" },
		-- 	{ "<leader>ll", mode = "n", "<cmd>LspLog<cr>", desc = "查看LSP日志" },
		-- },
		--
		-- opts = { -- 语言服务器配置
		-- 	servers = { -- 支持的编程语言列表
		-- 		-- clangd = {}, -- C/C++ 语言服务器
		-- 		-- pylsp = {}, -- Python 语言服务器
		-- 		-- lua_ls = {},
		-- 		-- bashls = {},
		-- 		-- ts_ls = {},
		-- 		-- sqls = {}, -- SQL 语言服务器
		-- 	}
		-- },
		--
		-- -- LSP配置与补全集成
		-- config = function(_, opts)
		-- 	local lspconfig = require('lspconfig')
		-- 	-- 为每个语言服务器注入补全能力
		-- 	for server, config in pairs(opts.servers) do
		-- 		-- config.capabilities = require('blink.cmp').get_lsp_capabilities(config.capabilities)
		-- 		vim.lsp.config(server, config)
		-- 		vim.lsp.enable(server)
		-- 	end
		-- end
	-- },
}
