return {
	-- {
	-- 	"mason-org/mason-lspconfig.nvim",
	-- 	dependencies = {
	-- 		{ "mason-org/mason.nvim", opts = { } },
	-- 		-- "neovim/nvim-lspconfig",
	-- 	},
	-- 	opts = {
	-- 		automatic_enable = true,
	-- 		ensure_installed = {
	-- 			"pylsp",
	-- 			"clangd",
	-- 			"lua_ls",
	-- 			"bashls",
	-- 			"html",
	-- 			"cssls",
	-- 			"ts_ls",
	-- 		}
	-- 	},
	-- }
}
