return {
	-- {
		-- "mfussenegger/nvim-dap",
		-- dependencies = {
		-- 	"mfussenegger/nvim-dap",
		-- },
	-- 	fr = {"c","cpp"},
	-- 	opts = function()
	-- 		local dap = require("dap")
	-- 		dap.adapters.codelldb = {
	-- 			type = "executable",
	-- 			command = "/home/luky/.local/share/nvim/mason/bin/codelldb", -- or if not in $PATH: "/absolute/path/to/codelldb"
	-- 		}
	-- 		dap.configurations.cpp = {
	-- 			{
	-- 				name = "Launch file",
	-- 				type = "codelldb",
	-- 				request = "launch",
	-- 				program = function()
	-- 					return vim.fn.input('Path to executable: ', vim.fn.getcwd() .. '/', 'file')
	-- 				end,
	-- 				cwd = '${workspaceFolder}',
	-- 				stopOnEntry = false,
	-- 			},
	-- 		}
	-- 		dap.configurations.c = dap.configurations.cpp
	-- 	end,
	-- }
}
